export const quizData = [
  {
    level: "beginner",
    title: "Grammar Basics",
    difficulty: "Easy",
    questions: [
      {
        question: "Choose the correct verb form:",
        text: "He ___ a student.",
        options: ["am", "is", "are", "be"],
        correctAnswer: 1,
        explanation:
          "'Is' is used with singular third person subjects (he, she, it).",
      },
      {
        question: "Choose the correct article:",
        text: "I saw ___ elephant in the zoo.",
        options: ["a", "an", "the", "no article"],
        correctAnswer: 1,
        explanation: "Use 'an' before words starting with a vowel sound.",
      },
      {
        question: "Choose the plural form:",
        text: "One child, two ___.",
        options: ["childs", "children", "childes", "childrens"],
        correctAnswer: 1,
        explanation: "The plural of child is 'children'.",
      },
      {
        question: "Select the past tense:",
        text: "Yesterday, she ___ to school.",
        options: ["go", "goes", "went", "gone"],
        correctAnswer: 2,
        explanation: "'Went' is the past tense of 'go'.",
      },
      {
        question: "Identify the adjective:",
        text: "She has a beautiful dress.",
        options: ["she", "has", "beautiful", "dress"],
        correctAnswer: 2,
        explanation:
          "Adjective describes a noun. Here 'beautiful' describes 'dress'.",
      },
    ],
  },
  {
    level: "beginner",
    title: "Everyday Vocabulary",
    difficulty: "Easy",
    questions: [
      {
        question: "Choose the word that means 'very big':",
        text: "The elephant is ___.",
        options: ["tiny", "enormous", "equal", "empty"],
        correctAnswer: 1,
        explanation: "'Enormous' means extremely large.",
      },
      {
        question: "Choose the synonym of 'happy':",
        text: "She felt very ___ after the exam.",
        options: ["sad", "joyful", "angry", "tired"],
        correctAnswer: 1,
        explanation: "'Joyful' means happy.",
      },
      {
        question: "Choose the antonym of 'hot':",
        text: "The water is too ___.",
        options: ["warm", "cold", "boiling", "heat"],
        correctAnswer: 1,
        explanation: "The opposite of hot is cold.",
      },
      {
        question: "Choose the correct option:",
        text: "You wear shoes on your ___.",
        options: ["head", "feet", "hands", "eyes"],
        correctAnswer: 1,
        explanation: "Shoes are worn on feet.",
      },
      {
        question: "Select the word related to food:",
        text: "Which of these is a fruit?",
        options: ["apple", "chair", "book", "shirt"],
        correctAnswer: 0,
        explanation: "Apple is a fruit.",
      },
      {
        question: "Choose the correct spelling:",
        text: "Which one is correct?",
        options: ["recieve", "receive", "receeve", "receve"],
        correctAnswer: 1,
        explanation: "The correct spelling is 'receive'.",
      },
    ],
  },
  {
    level: "beginner",
    title: "Simple Tenses",
    difficulty: "Easy",
    questions: [
      {
        question: "Choose the present tense:",
        text: "She ___ English every day.",
        options: ["study", "studies", "studied", "studying"],
        correctAnswer: 1,
        explanation:
          "'She studies' is correct as third person singular takes -s.",
      },
      {
        question: "Choose the past tense:",
        text: "He ___ football yesterday.",
        options: ["play", "plays", "played", "playing"],
        correctAnswer: 2,
        explanation: "The past tense of play is 'played'.",
      },
      {
        question: "Choose the future tense:",
        text: "I ___ visit London next year.",
        options: ["will", "was", "am", "did"],
        correctAnswer: 0,
        explanation: "Use 'will' for simple future tense.",
      },
      {
        question: "Fill in the blank:",
        text: "They ___ watching TV right now.",
        options: ["is", "are", "am", "be"],
        correctAnswer: 1,
        explanation: "With 'they', use 'are'.",
      },
      {
        question: "Choose the negative form:",
        text: "She ___ like pizza.",
        options: ["don't", "doesn't", "isn't", "not"],
        correctAnswer: 1,
        explanation: "For third person singular, use 'doesn't'.",
      },
      {
        question: "Identify tense:",
        text: "I have finished my homework.",
        options: [
          "Present simple",
          "Present continuous",
          "Present perfect",
          "Past simple",
        ],
        correctAnswer: 2,
        explanation: "'Have finished' is present perfect tense.",
      },
    ],
  },
  {
    level: "beginner",
    title: "Common Expressions",
    difficulty: "Easy",
    questions: [
      {
        question: "What does 'Good morning' mean?",
        text: "It is used when:",
        options: [
          "You go to bed",
          "You meet someone in the morning",
          "You leave a party",
          "You are angry",
        ],
        correctAnswer: 1,
        explanation: "'Good morning' is used as a greeting in the morning.",
      },
      {
        question: "Choose the polite response:",
        text: "If someone says 'Thank you', you reply:",
        options: ["No", "Yes", "You're welcome", "Okay"],
        correctAnswer: 2,
        explanation: "Polite response is 'You're welcome'.",
      },
      {
        question: "What does 'Excuse me' mean?",
        text: "It is used when:",
        options: [
          "You are happy",
          "You want attention or to pass",
          "You are angry",
          "You are sad",
        ],
        correctAnswer: 1,
        explanation: "'Excuse me' is used to politely get attention or pass.",
      },
      {
        question: "What does 'How are you?' mean?",
        text: "It is:",
        options: [
          "Asking about health/feelings",
          "Asking name",
          "Asking place",
          "Asking age",
        ],
        correctAnswer: 0,
        explanation: "'How are you?' asks about a person's well-being.",
      },
      {
        question: "Choose the correct response:",
        text: "If someone says 'See you later', you say:",
        options: ["Bye", "See you", "Good night", "Hello"],
        correctAnswer: 1,
        explanation: "'See you later' is replied with 'See you'.",
      },
    ],
  },
  {
    level: "beginner",
    title: "Numbers and Time",
    difficulty: "Easy",
    questions: [
      {
        question: "Choose the correct number:",
        text: "Ten plus five is ___.",
        options: ["14", "15", "16", "20"],
        correctAnswer: 1,
        explanation: "10 + 5 = 15.",
      },
      {
        question: "What time is 'half past six'?",
        text: "It means:",
        options: ["5:30", "6:30", "7:30", "6:15"],
        correctAnswer: 1,
        explanation: "'Half past six' means 6:30.",
      },
      {
        question: "Which number is even?",
        text: "Choose:",
        options: ["3", "7", "8", "11"],
        correctAnswer: 2,
        explanation: "8 is even.",
      },
      {
        question: "How many days in a week?",
        text: "Choose:",
        options: ["5", "6", "7", "10"],
        correctAnswer: 2,
        explanation: "A week has 7 days.",
      },
      {
        question: "Which is the first month of the year?",
        text: "Choose:",
        options: ["January", "March", "April", "December"],
        correctAnswer: 0,
        explanation: "The first month is January.",
      },
      {
        question: "Choose the correct ordinal number:",
        text: "Sunday is the ___ day of the week (in many countries).",
        options: ["first", "second", "third", "last"],
        correctAnswer: 0,
        explanation: "Sunday is considered the first day in many calendars.",
      },
    ],
  },
  {
    level: "beginner",
    title: "Basic Pronouns",
    difficulty: "Easy",
    questions: [
      {
        question: "Choose the correct pronoun:",
        text: "___ am a student.",
        options: ["He", "She", "I", "They"],
        correctAnswer: 2,
        explanation: "Use 'I' when referring to yourself.",
      },
      {
        question: "Choose the correct pronoun:",
        text: "This is my brother. ___ is tall.",
        options: ["He", "She", "It", "They"],
        correctAnswer: 0,
        explanation: "For male singular, use 'He'.",
      },
      {
        question: "Choose the object pronoun:",
        text: "She is looking at ___.",
        options: ["he", "him", "his", "they"],
        correctAnswer: 1,
        explanation: "'Him' is the object pronoun for 'he'.",
      },
      {
        question: "Choose the possessive pronoun:",
        text: "This book is ___.",
        options: ["I", "me", "mine", "my"],
        correctAnswer: 2,
        explanation: "'Mine' shows possession.",
      },
      {
        question: "Choose the plural pronoun:",
        text: "___ are my friends.",
        options: ["He", "She", "They", "It"],
        correctAnswer: 2,
        explanation: "'They' is used for plural people/objects.",
      },
      {
        question: "Choose the demonstrative pronoun:",
        text: "___ is my bag.",
        options: ["This", "He", "She", "I"],
        correctAnswer: 0,
        explanation: "'This' is used for something near the speaker.",
      },
    ],
  },
];
