export const videoLessons = [
  {
    id: 1,
    level: "beginner",
    title: "How to use have, has, had",
    duration: "10:46",
    completed: false,
    points: 75,
    url: "https://www.youtube.com/embed/XTYRwP21QyE?si=YmNSKDk7tOpu-UcH",
  },
  {
    id: 2,
    level: "beginner",
    title: "Basic Verbs: to be and to have",
    duration: "29:10",
    completed: true,
    points: 50,
    url: "https://www.youtube.com/embed/wBP91ksa6Mw?si=5alUwj3_KjZQRR2o",
  },
  {
    id: 3,
    level: "beginner",
    title: "How to use was and were",
    duration: "15:38",
    completed: true,
    points: 30,
    url: "https://www.youtube.com/embed/MNdeEtZ5jBc?si=3fQgOZ5V7A_WULSn",
  },

  {
    id: 4,
    level: "beginner",
    title: "how to use can, could, may, might",
    duration: "10:34",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/sKQtU7JTtMQ?si=UzrrxgOFFGqr8Xit",
  },

  {
    id: 5,
    level: "intermediate",
    title: "English Speaking Tips",
    duration: "15:28",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/BGtQ2VuzAIY?si=43dl4FVmvazH7urf",
  },
  {
    id: 6,
    level: "intermediate",
    title: "7 tips to Improve your English",
    duration: "18:04",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/EBgwZ0rSkcQ?si=ZUM9Ju25pZnOmpsc",
  },
  {
    id: 7,
    level: "intermediate",
    title: "Practice Alone at home",
    duration: "12:19",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/tocW8NioHOY?si=UKF6MA2hzBOpVt6_",
  },
  {
    id: 8,
    level: "advanced",
    title: "Speak FLUENT English",
    duration: "21:52",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/zYSHxmgHmfg?si=h_BTFjAIc-xzWwvm",
  },
  {
    id: 9,
    level: "advanced",
    title: "English Speaking Practice with Neutral Accent",
    duration: "15:00",
    completed: false,
    points: 40,
    url: "https://www.youtube.com/embed/LZy-cFtEWGs?si=4oP-LDYN-SnkHBiT",
  },
];
